const stations = [
//     // {
//     //     "StationId": 1,
//     //     "StationName": "Abisko Scientific Research Station",
//     //     "Contact": null,
//     //     "Website": "https://www.polar.se/stoed-till-polarforskning/abisko-naturvetenskapliga-station",
//     //     "Email": "ans@polar.se",
//     //     "AdminId": null,
//     //     "Terms": "abisko.pdf",
//     //     "Acronym": "ANS",
//     //     "Confirm": null,
//     //     "Reject": null,
//     //     "Image": "abisko2.jpg",
//     //     "HasSignedGPDRContract": false,
//     //     "Latitude": 68.35461100,
//     //     "Longitude": 18.81591700
//     // },
    {
        "StationId": 2,
        "StationName": "Tarfala Research Station",
        "Contact": null,
        "Website": "www.tarfala.su.se ",
        "Email": "tarfala@natgeo.su.se",
        "AdminId": null,
        "Terms": "TRS_Terms and Conditions 2020.pdf",
        "Acronym": "TRS",
        "Confirm": null,
        "Reject": null,
        "Image": "20210423_113754.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 67.91666666,
        "Longitude": 18.58333333
    },
//     // {
//     //     "StationId": 9,
//     //     "StationName": "Svartberget research station",
//     //     "Contact": null,
//     //     "Website": "https://www.slu.se/svartberget",
//     //     "Email": "charlotta.erefur@slu.se",
//     //     "AdminId": null,
//     //     "Terms": "svartberget.pdf",
//     //     "Acronym": "SVB",
//     //     "Confirm": null,
//     //     "Reject": null,
//     //     "Image": "svartberget.jpg",
//     //     "HasSignedGPDRContract": false,
//     //     "Latitude": 64.24434000,
//     //     "Longitude": 19.76646000
//     // },
//     // {
//     //     "StationId": 11,
//     //     "StationName": "Sverdrup Research Station ",
//     //     "Contact": null,
//     //     "Website": "http://sverdrup.npolar.no ",
//     //     "Email": "headnpi.nya@npolar.no",
//     //     "AdminId": null,
//     //     "Terms": null,
//     //     "Acronym": "SVERDR",
//     //     "Confirm": null,
//     //     "Reject": null,
//     //     "Image": "Sverdrup_Cable-car_Li-Gang-975x400.jpg",
//     //     "HasSignedGPDRContract": false,
//     //     "Latitude": 78.91666666,
//     //     "Longitude": 11.93333333
//     // },
    {
        "StationId": 12,
        "StationName": "Netherlands’ Arctic Station ",
        "Contact": null,
        "Website": "www.arcticstation.nl ",
        "Email": "m.j.j.e.loonen@rug.nl",
        "AdminId": null,
        "Terms": null,
        "Acronym": "NLAS",
        "Confirm": null,
        "Reject": null,
        "Image": "arcticstation.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 78.91666666,
        "Longitude": 11.93333333
    },
//     {
//         "StationId": 13,
//         "StationName": "UK Arctic Research Station ",
//         "Contact": null,
//         "Website": "www.arctic.ac.uk ",
//         "Email": "nc@bas.ac.uk",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "UKARS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "UK-Arctic-Station_Station-building_Nick_Cox-975x400.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 78.91666666,
//         "Longitude": 11.93333333
//     },
//     {
//         "StationId": 14,
//         "StationName": "CNR Arctic Station \"Dirigibile Italia\"",
//         "Contact": null,
//         "Website": "www.polarnet.cnr.it/content/view/162/58/lang,en",
//         "Email": "dacqui@ise.cnr.it",
//         "AdminId": null,
//         "Terms": "cnr.pdf",
//         "Acronym": "CNR",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "cnr.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 78.91666666,
//         "Longitude": 11.93333333
//     },
//     {
//         "StationId": 15,
//         "StationName": "Czech Arctic Research Station of Josef Svoboda",
//         "Contact": null,
//         "Website": "http://polar.prf.jcu.cz/station.htm ",
//         "Email": "cars@prf.jcu.cz",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CzARS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "czech5616b_a1.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 78.66666666,
//         "Longitude": 16.38333333
//     },
    {
        "StationId": 16,
        "StationName": "Hornsund Polish Polar Station",
        "Contact": null,
        "Website": "www.hornsund.pl",
        "Email": "polar@igf.edu.pl",
        "AdminId": null,
        "Terms": null,
        "Acronym": "HOR",
        "Confirm": null,
        "Reject": null,
        "Image": "hornsund-slide1.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 77.00000000,
        "Longitude": 15.55000000
    },
//     {
//         "StationId": 17,
//         "StationName": "Finse Alpine Research Centre",
//         "Contact": null,
//         "Website": "www.finse.uio.no ",
//         "Email": "torbjorn.ergon@bio.uio.no",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Finse",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "finse.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 60.60000000,
//         "Longitude": 7.50000000
//     },
//     {
//         "StationId": 18,
//         "StationName": "Bioforsk Svanhovd Research Station ",
//         "Contact": null,
//         "Website": "www.bioforsk.no/svanhovd ",
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": null,
//         "Confirm": null,
//         "Reject": null,
//         "Image": "svanhovd.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 69.45000000,
//         "Longitude": 30.05000000
//     },
//     {
//         "StationId": 19,
//         "StationName": "Kilpisjärvi Biological Station ",
//         "Contact": null,
//         "Website": "www.helsinki.fi/kilpis ",
//         "Email": "bio-kilpis@helsinki.fi",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Kilp",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "kipisjarvi.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 69.05000000,
//         "Longitude": 20.83333333
//     },
    {
        "StationId": 20,
        "StationName": "Kevo Subarctic Research Station",
        "Contact": null,
        "Website": "www.utu.fi/en/units/cerut/kevo",
        "Email": "kevo@utu.fi",
        "AdminId": null,
        "Terms": null,
        "Acronym": "Kevo",
        "Confirm": null,
        "Reject": null,
        "Image": "kevo.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 69.75000000,
        "Longitude": 27.01666666
    },
//     {
//         "StationId": 21,
//         "StationName": "Värriö Subarctic Research Station",
//         "Contact": null,
//         "Website": "www.atm.helsinki.fi/varrio/fi",
//         "Email": "kimmo.neitola@helsinki.fi",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "SMEAR I",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "varrio.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 67.73333333,
//         "Longitude": 29.60000000
//     },
    {
        "StationId": 22,
        "StationName": "Pallas-Sodankylä Research Station",
        "Contact": null,
        "Website": "http://fmiarc.fmi.fi",
        "Email": "Leena.Leppanen@fmi.fi",
        "AdminId": null,
        "Terms": null,
        "Acronym": "PallSod",
        "Confirm": null,
        "Reject": null,
        "Image": "pallas.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 67.36666666,
        "Longitude": 26.65000000
    },
//     {
//         "StationId": 23,
//         "StationName": "Kolari Research Unit",
//         "Contact": null,
//         "Website": "www.luke.fi/en",
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": null,
//         "Confirm": null,
//         "Reject": null,
//         "Image": "kolari.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 67.35000000,
//         "Longitude": 23.81666666
//     },
//     {
//         "StationId": 24,
//         "StationName": "Oulanka Research Station ",
//         "Contact": null,
//         "Website": "www.oulu.fi/oulankaresearchstation",
//         "Email": "oulanka@oulu.fi",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Oulanka",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "oulanka.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 66.36666666,
//         "Longitude": 29.31666666
//     },
//     {
//         "StationId": 25,
//         "StationName": "Kainuu Fisheries Research Station",
//         "Contact": null,
//         "Website": "www.kfrs.fi",
//         "Email": "pekka.hyvarinen@luke.fi",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Kainuu",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "kainuu.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 64.40000000,
//         "Longitude": 27.50000000
//     },
//     {
//         "StationId": 26,
//         "StationName": "Hyytiälä Forest Research Station (SMEAR II)",
//         "Contact": null,
//         "Website": "https://www.helsinki.fi/en/research-stations/hyytiala-forestry-field-station",
//         "Email": "jaana.back@helsinki.fi",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Hyyt",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "hyytiala.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 61.85000000,
//         "Longitude": 24.28333333
//     },
//     {
//         "StationId": 27,
//         "StationName": "ALPFOR Alpine Research and Education Station Furka ",
//         "Contact": null,
//         "Website": "http://pages.unibas.ch/botschoen/alpfor ",
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": null,
//         "Confirm": null,
//         "Reject": null,
//         "Image": "alpfor.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 46.56666666,
//         "Longitude": 8.41666666
//     },
    {
        "StationId": 28,
        "StationName": "Station Hintereis ",
        "Contact": null,
        "Website": "https://www.uibk.ac.at/projects/station-hintereis-opal-data/index.html.en",
        "Email": "rainer.prinz@uibk.ac.at",
        "AdminId": null,
        "Terms": null,
        "Acronym": "St-HE",
        "Confirm": null,
        "Reject": null,
        "Image": "130416_ST-HE_outside_rp.JPG",
        "HasSignedGPDRContract": false,
        "Latitude": 46.79864500,
        "Longitude": 10.76058700
    },
//     {
//         "StationId": 29,
//         "StationName": "Sonnblick Observatory ",
//         "Contact": null,
//         "Website": "www.sonnblick.net ",
//         "Email": "elke.ludewig@zamg.ac.at",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "SONNBLICK",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "sonnblick.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 47.05000000,
//         "Longitude": 12.95000000
//     },
//     {
//         "StationId": 30,
//         "StationName": "Krkonoše (CZ)/Karkonosze (PL) National Parks",
//         "Contact": null,
//         "Website": "www.krnap.cz, www.kpnmab.pl ",
//         "Email": "marek.dobrowolski@kpnmab.pl",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Krk",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "krkonose.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 50.73333333,
//         "Longitude": 15.73333333
//     },
    {
        "StationId": 31,
        "StationName": "M.M. Kłapa Research Station",
        "Contact": null,
        "Website": "www.igipz.pan.pl/hala-gasienicowa-zbg.html",
        "Email": "raczk@zg.pan.krakow.pl",
        "AdminId": null,
        "Terms": null,
        "Acronym": "M&M",
        "Confirm": null,
        "Reject": null,
        "Image": "mm-klapa-687x400.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 49.24421390,
        "Longitude": 20.00566390
    },
//     {
//         "StationId": 32,
//         "StationName": "Khibiny Educational and Scientific Station ",
//         "Contact": null,
//         "Website": "www.eng.geogr.msu.ru/practics/stations/khibiny",
//         "Email": "yzaika@inbox.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "KESS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "khibiny.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 67.63776670,
//         "Longitude": 33.72550000
//     },
//     {
//         "StationId": 33,
//         "StationName": "Beliy Island Research Station",
//         "Contact": null,
//         "Website": "www.arctic-rf.ru (in Russian)",
//         "Email": "vp256@mail.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "BIRS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "beliy.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 73.06655560,
//         "Longitude": 69.95266670
//     },
//     {
//         "StationId": 34,
//         "StationName": "The Arctic Research Station ",
//         "Contact": null,
//         "Website": "– ",
//         "Email": "sokhol@yandex.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "ARS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "labytnangi.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 66.65958330,
//         "Longitude": 66.40886110
//     },
//     {
//         "StationId": 35,
//         "StationName": "Numto Park Station",
//         "Contact": null,
//         "Website": "https://mukhrinostation.com/",
//         "Email": "filippova.courlee.nina@gmail.com",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "NPS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "SafarovMYu (2).jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 63.37709000,
//         "Longitude": 70.62700280
//     },
//     {
//         "StationId": 36,
//         "StationName": "Mukhrino Field Station",
//         "Contact": null,
//         "Website": "https://mukhrinostation.com/",
//         "Email": "filippova.courlee.nina@gmail.com",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "MFS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "MFS_polygon_Постер_сжато.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 60.88890000,
//         "Longitude": 68.70260000
//     },
//     {
//         "StationId": 37,
//         "StationName": "Willem Barentsz Biological Station",
//         "Contact": null,
//         "Website": "http://zapovedsever.ru (owner institution’s website in Russian)",
//         "Email": "mikhail-soloviev@yandex.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "WBBS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "willembarents.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 73.35950560,
//         "Longitude": 80.54084170
//     },
//     {
//         "StationId": 38,
//         "StationName": "Khanymei Research Station",
//         "Contact": null,
//         "Website": "http://www.secnet.online/khanymei-eng.html",
//         "Email": "kirp@mail.tsu.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Khanymei",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "khanymei.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 63.40890750,
//         "Longitude": 71.30478720
//     },
//     {
//         "StationId": 39,
//         "StationName": "Kajbasovo Research Station",
//         "Contact": null,
//         "Website": "http://en.science.tsu.ru/units/research-stations/",
//         "Email": "kirp@mail.tsu.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "KRS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "Kajbasovo-station-during-spring-floof-from-dron-975x400.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 57.14453800,
//         "Longitude": 84.11061700
//     },
//     {
//         "StationId": 40,
//         "StationName": "Igarka Geocryology Laboratory ",
//         "Contact": null,
//         "Website": "http://mpi.ysn.ru/index.php/news/39 ",
//         "Email": "nikita.tananaev@gmail.com",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "IGL",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "igarka.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 67.45294440,
//         "Longitude": 86.53522220
//     },
//     {
//         "StationId": 41,
//         "StationName": "Aktru Research Station ",
//         "Contact": null,
//         "Website": "http://en.science.tsu.ru/units/research-stations/",
//         "Email": "kirp@mail.tsu.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Aktru",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "aktru.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 50.08359720,
//         "Longitude": 87.77935280
//     },
//     {
//         "StationId": 42,
//         "StationName": "Evenkian Field Station",
//         "Contact": null,
//         "Website": "http://forest.akadem.ru/State/EVE.html",
//         "Email": "prokushkin@ksc.krasn.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "EFS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "evenkian.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 64.28333333,
//         "Longitude": 100.18333333
//     },
//     {
//         "StationId": 43,
//         "StationName": "International Ecological Educational Center \"Istomino\"",
//         "Contact": null,
//         "Website": "www.binm.ru, http://binm.ru/istomino/en",
//         "Email": "aaayurzhanaev@yandex.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "IEEC Istomino",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "istomino-2.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 52.13333333,
//         "Longitude": 106.28333333
//     },
//     {
//         "StationId": 44,
//         "StationName": "Research Station Samoylov Island",
//         "Contact": null,
//         "Website": "https://www.awi.de/en/expedition/stations/island-samoylov; http://samoylov-island.ru/en/",
//         "Email": "tsibizovlv@ipgg.sbras.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "RSSI",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "DSC06956_Research-Station-Samoylov-Island_Anne-Morgenstern.JPG",
//         "HasSignedGPDRContract": false,
//         "Latitude": 72.36666666,
//         "Longitude": 126.48333333
//     },
//     {
//         "StationId": 45,
//         "StationName": "Spasskaya Pad Scientific Forest Station",
//         "Contact": null,
//         "Website": "http://ibpc.ysn.ru/%d1%81%d1%82%d0%b0%d1%86%d0%b8%d0%be%d0%bd%d0%b0%d1%80%d1%8b/%d1%81%d0%bf%d0%b0%d1%81%d1%81%d0%ba%d0%b0%d1%8f-%d0%bf%d0%b0%d0%b4%d1%8c/",
//         "Email": "t.c.maximov@ibpc.ysn.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "SPSFS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "spasskaya.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 62.23333333,
//         "Longitude": 129.61666666
//     },
//     {
//         "StationId": 46,
//         "StationName": "Elgeeii Scientific Forest Station",
//         "Contact": null,
//         "Website": "http://ibpc.ysn.ru/?page_id=231",
//         "Email": "tcmax@mail.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "ESFS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "elgeeii.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 60.01666666,
//         "Longitude": 133.81666666
//     },
//     {
//         "StationId": 47,
//         "StationName": "Chokurdakh Scientific Tundra Station",
//         "Contact": null,
//         "Website": "-",
//         "Email": "t.c.maximov@ibpc.ysn.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CSTS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "chokurdakh.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 70.81666666,
//         "Longitude": 147.48333333
//     },
//     {
//         "StationId": 48,
//         "StationName": "Orotuk Field Station",
//         "Contact": null,
//         "Website": "www.ibpn.ru/en/field-stations",
//         "Email": "meks_mag@mail.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "OFS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "orotuk.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 62.05000000,
//         "Longitude": 148.65000000
//     },
//     {
//         "StationId": 49,
//         "StationName": "North-East Science Station (NESS) ",
//         "Contact": null,
//         "Website": "www.pleistocenepark.ru",
//         "Email": "nzimov@mail.ru",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "NESS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "northeast.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 68.08333333,
//         "Longitude": 161.08333333
//     },
//     {
//         "StationId": 50,
//         "StationName": "Avachinsky Volcano Field Station",
//         "Contact": null,
//         "Website": "http://vulcanikamchatki.ru/territoriya/klaster_nalychevskij",
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": null,
//         "Confirm": null,
//         "Reject": null,
//         "Image": "avachinsky.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 53.25000000,
//         "Longitude": 158.73333333
//     },
//     {
//         "StationId": 51,
//         "StationName": "Meinypil\’gyno Community Based Biological Station",
//         "Contact": null,
//         "Website": "www.birdsrussia.ru (information in English will be added soon)",
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": null,
//         "Confirm": null,
//         "Reject": null,
//         "Image": "meinypilgyno.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 62.53333333,
//         "Longitude": 177.05000000
//     },
//     {
//         "StationId": 52,
//         "StationName": "Adygine Research Station",
//         "Contact": null,
//         "Website": "https://www.geomin.cz/adygine/?jazyk=en&menu=20",
//         "Email": "adyginefund@adygine.com",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Adygine",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "adygine.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 42.50000000,
//         "Longitude": 74.58333333
//     },
//     {
//         "StationId": 53,
//         "StationName": "Barrow Arctic Research Center/Barrow Environmental Observatory ",
//         "Contact": null,
//         "Website": "www.barrowbulletin.com",
//         "Email": "nagruk.harcharek@uicscience.com",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "BARC",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "barrow.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 71.30000000,
//         "Longitude": -156.58333333
//     },
    {
        "StationId": 54,
        "StationName": "Toolik Field Station ",
        "Contact": null,
        "Website": "http://toolik.alaska.edu ",
        "Email": null,
        "AdminId": null,
        "Terms": null,
        "Acronym": null,
        "Confirm": null,
        "Reject": null,
        "Image": "toolik.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 68.61666666,
        "Longitude": -149.58333333
    },
    {
        "StationId": 55,
        "StationName": "Kluane Lake Research Station",
        "Contact": null,
        "Website": "www.arctic.ucalgary.ca/research/kluane-lake-research-station ",
        "Email": "klrs@ucalgary.ca",
        "AdminId": null,
        "Terms": null,
        "Acronym": "Kluane",
        "Confirm": null,
        "Reject": null,
        "Image": "kluanelake.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 61.01666666,
        "Longitude": -138.40000000
    },
    {
        "StationId": 56,
        "StationName": "Western Arctic Research Centre (WARC)",
        "Contact": null,
        "Website": "http://nwtresearch.com",
        "Email": "warc@auroracollege.nt.ca",
        "AdminId": null,
        "Terms": null,
        "Acronym": "WARC",
        "Confirm": null,
        "Reject": null,
        "Image": "warc.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 68.35000000,
        "Longitude": -133.71666666
    },
//     {
//         "StationId": 57,
//         "StationName": "Canadian High Arctic Research Station campus",
//         "Contact": null,
//         "Website": "https://www.canada.ca/en/polar-knowledge.html",
//         "Email": "researchsupport-soutienalarecherche@polar-polaire.gc.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CHARS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "CHARS at night-.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 69.12086400,
//         "Longitude": -105.04199800
//     },
//     {
//         "StationId": 58,
//         "StationName": "M\’Clintock Channel Polar Research Cabins",
//         "Contact": null,
//         "Website": "–",
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": null,
//         "Confirm": null,
//         "Reject": null,
//         "Image": null,
//         "HasSignedGPDRContract": false,
//         "Latitude": 68.61666666,
//         "Longitude": -95.86666666
//     },
//     {
//         "StationId": 59,
//         "StationName": "Flashline Mars Arctic Research Station",
//         "Contact": null,
//         "Website": "www.fmars.marssociety.org",
//         "Email": "info@marssociety.org",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Mars",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "Flashline-Mars-975x400.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 75.41666666,
//         "Longitude": -89.81666666
//     },
//     {
//         "StationId": 60,
//         "StationName": "Polar Environment Atmospheric Research Laboratory (PEARL)",
//         "Contact": null,
//         "Website": "www.candac.ca",
//         "Email": "james.drummond@dal.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "PEARL",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "pearl.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 79.98333333,
//         "Longitude": -85.80000000
//     },
//     {
//         "StationId": 61,
//         "StationName": "CEN Ward Hunt Island Research Station",
//         "Contact": null,
//         "Website": "http://www.cen.ulaval.ca/en/station.php?id=326&nm=wardhunt",
//         "Email": "cen@cen.ulaval.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CEN WH",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "CEN Ward Hunt lab_DSarrazin.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 83.10000000,
//         "Longitude": -74.16666666
//     },
//     {
//         "StationId": 62,
//         "StationName": "CEN Bylot Island Field Station",
//         "Contact": null,
//         "Website": "www.cen.ulaval.ca/bylot",
//         "Email": "cen@cen.ulaval.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CEN Bylot",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "bylotisland.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 73.13333333,
//         "Longitude": -80.00000000
//     },
//     {
//         "StationId": 63,
//         "StationName": "Igloolik Research Center ",
//         "Contact": null,
//         "Website": "http://env.gov.nu.ca/wildlife/resources",
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": null,
//         "Confirm": null,
//         "Reject": null,
//         "Image": "igloolik.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 69.36666666,
//         "Longitude": -81.80000000
//     },
//     {
//         "StationId": 64,
//         "StationName": "CEN Salluit Research Station",
//         "Contact": null,
//         "Website": "www.cen.ulaval.ca/en/page.aspx?lien=stationsalluit ",
//         "Email": "station@cen.ulaval.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CEN Salluit",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "RFortier1.JPG",
//         "HasSignedGPDRContract": false,
//         "Latitude": 62.20000000,
//         "Longitude": -75.63333333
//     },
//     {
//         "StationId": 65,
//         "StationName": "CEN Boniface River Field Station ",
//         "Contact": null,
//         "Website": "http://www.cen.ulaval.ca/en/station.php?id=327&nm=boniface",
//         "Email": "station@cen.ulaval.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CEN Boniface",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "Station de recherche_Boniface.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 57.75000000,
//         "Longitude": -76.16666666
//     },
//     {
//         "StationId": 66,
//         "StationName": "CEN Umiujaq Research Station",
//         "Contact": null,
//         "Website": "www.cen.ulaval.ca/en/page.aspx?lien=stationumiujaq ",
//         "Email": "station@cen.ulaval.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CEN Umiujaq",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "RFortier Umiujaq2.JPG",
//         "HasSignedGPDRContract": false,
//         "Latitude": 56.55000000,
//         "Longitude": -76.53333333
//     },
//     {
//         "StationId": 67,
//         "StationName": "CEN Whapmagoostui-Kuujjuarapik Research Station",
//         "Contact": null,
//         "Website": "www.cen.ulaval.ca/en/page.aspx?lien=stationkuujjuarapik ",
//         "Email": "station@cen.ulaval.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CEN WK",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "Denis Sarrazin_WK station fev2013.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 55.26666666,
//         "Longitude": -77.75000000
//     },
//     {
//         "StationId": 68,
//         "StationName": "CEN Radisson Ecological Research Station",
//         "Contact": null,
//         "Website": "www.cen.ulaval.ca/en/page.aspx?lien=stationradisson ",
//         "Email": "station@cen.ulaval.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CEN Radisson",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "radisson.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 53.78333333,
//         "Longitude": -77.61666666
//     },
//     {
//         "StationId": 69,
//         "StationName": "CEN Wiyâshâkimî Lake (Clearwater Lake) Research Station",
//         "Contact": null,
//         "Website": "http://www.cen.ulaval.ca/en/station.php?id=323&nm=lec",
//         "Email": "station@cen.ulaval.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CEN Lake Wiyâshâkimî",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "LEC1.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 56.33333333,
//         "Longitude": -74.45000000
//     },
//     {
//         "StationId": 70,
//         "StationName": "Nunavut Research Institute",
//         "Contact": null,
//         "Website": "www.nri.ca",
//         "Email": "maryellen.thomas@arcticcollege.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "NRI",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "Nunavut_Research_Institute-640x400.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 63.75000000,
//         "Longitude": -68.51666666
//     },
//     {
//         "StationId": 71,
//         "StationName": "Labrador Institute Research Station (LIRS)",
//         "Contact": null,
//         "Website": "www.mun.ca/labradorinstitute",
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": null,
//         "Confirm": null,
//         "Reject": null,
//         "Image": null,
//         "HasSignedGPDRContract": false,
//         "Latitude": 53.51666666,
//         "Longitude": -60.13333333
//     },
//     {
//         "StationId": 72,
//         "StationName": "Arctic Station ",
//         "Contact": null,
//         "Website": "http://arktiskstation.ku.dk/english",
//         "Email": "gin@science.ku.dk",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "ArcticSt",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "Arctic-station-Greenland-thumb-e1510071924525-507x400.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 69.25000000,
//         "Longitude": -53.56666666
//     },
    {
        "StationId": 73,
        "StationName": "Greenland Institute of Natural Resources (GINR)",
        "Contact": null,
        "Website": "www.natur.gl, www.g-e-m.dk",
        "Email": "booking@natur.gl",
        "AdminId": null,
        "Terms": null,
        "Acronym": "GINR",
        "Confirm": null,
        "Reject": null,
        "Image": "greenlandinstitute.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 64.19051980,
        "Longitude": -51.69725140
    },
//     {
//         "StationId": 74,
//         "StationName": "Sermilik Research Station ",
//         "Contact": null,
//         "Website": "www.geo.ku.dk ",
//         "Email": "ak@ign.ku.dk",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Serm",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "sermilik.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 65.66666666,
//         "Longitude": -38.16666666
//     },
//     {
//         "StationId": 75,
//         "StationName": "Summit Station",
//         "Contact": null,
//         "Website": "www.geosummit.org, www.summitcamp.org",
//         "Email": "sco@summitcamp.org",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Summ",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "Summit-Station_Ed-Stockard-975x400.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 72.57958250,
//         "Longitude": -38.46794070
//     },
//     {
//         "StationId": 76,
//         "StationName": "EGRIP Field Station",
//         "Contact": null,
//         "Website": "www.iceandclimate.nbi.ku.dk",
//         "Email": "ddj@nbi.ku.dk",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "EGRIP",
//         "Confirm": null,
//         "Reject": null,
//         "Image": null,
//         "HasSignedGPDRContract": false,
//         "Latitude": 75.38000000,
//         "Longitude": -36.00000000
//     },
    {
        "StationId": 77,
        "StationName": "Zackenberg Research Station ",
        "Contact": null,
        "Website": "www.zackenberg.dk, www.g-e-m.dk ",
        "Email": "zackenberg@au.dk",
        "AdminId": null,
        "Terms": null,
        "Acronym": "ZRS",
        "Confirm": null,
        "Reject": null,
        "Image": "zackenberg.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 74.50235120,
        "Longitude": -23.00795200
    },
//     {
//         "StationId": 78,
//         "StationName": "Villum Research Station (VRS)",
//         "Contact": null,
//         "Website": "https://villumresearchstation.dk/",
//         "Email": "secretariat@villumresearchstation.au.dk",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Villum",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "villum.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 81.60000000,
//         "Longitude": -16.65000000
//     },
    {
        "StationId": 79,
        "StationName": "Suðurnes Science and Learning Center",
        "Contact": null,
        "Website": "www.thekkingarsetur.is",
        "Email": "thekkingarsetur@thekkingarsetur.is",
        "AdminId": null,
        "Terms": null,
        "Acronym": "SSLC",
        "Confirm": null,
        "Reject": null,
        "Image": "sudurnes.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 64.03333333,
        "Longitude": -22.70000000
    },
//     {
//         "StationId": 80,
//         "StationName": "Litla-Skarð",
//         "Contact": null,
//         "Website": "www.ust.is/litla_skard",
//         "Email": "hlynur@lbhi.is",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "L-Sk",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "litlaskard.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 64.71666666,
//         "Longitude": -21.61666666
//     },
//     {
//         "StationId": 81,
//         "StationName": "Kárhóll Research Station",
//         "Contact": null,
//         "Website": null,
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": null,
//         "Confirm": null,
//         "Reject": null,
//         "Image": null,
//         "HasSignedGPDRContract": false,
//         "Latitude": 65.72299410,
//         "Longitude": -17.36775450
//     },
    {
        "StationId": 82,
        "StationName": "Rif Field Station",
        "Contact": null,
        "Website": "https://rifresearch.is/",
        "Email": "rif@rifresearch.is",
        "AdminId": null,
        "Terms": null,
        "Acronym": "RFS",
        "Confirm": null,
        "Reject": null,
        "Image": "rif.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 66.51666666,
        "Longitude": -16.18333333
    },
    {
        "StationId": 83,
        "StationName": "Faroe Islands Nature Investigation (FINI)",
        "Contact": null,
        "Website": "www.jf.fo ",
        "Email": "lm@jf.fo",
        "AdminId": null,
        "Terms": null,
        "Acronym": "FINI",
        "Confirm": null,
        "Reject": null,
        "Image": "fini.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 62.06666666,
        "Longitude": -6.96666666
    },
//     {
//         "StationId": 84,
//         "StationName": "Cairngorms",
//         "Contact": null,
//         "Website": "www.ecn.ac.uk ",
//         "Email": "jand@ceh.ac.uk",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "Cairn",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "cairngorm.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 57.11666666,
//         "Longitude": -3.81666666
//     },
//     {
//         "StationId": 85,
//         "StationName": "UAPISHKA RESEARCH STATION",
//         "Contact": null,
//         "Website": "https://stationuapishka.com/",
//         "Email": "gproulx@rmbmu.com",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "UAP",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "Capture d’écran, le 2019-09-12 à 15.34.12.png",
//         "HasSignedGPDRContract": false,
//         "Latitude": 51.46444900,
//         "Longitude": -68.23575200
//     },
//     {
//         "StationId": 86,
//         "StationName": "Lammin Suo Research Station",
//         "Contact": null,
//         "Website": null,
//         "Email": "hydromod@gmail.com",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "LSRS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": null,
//         "HasSignedGPDRContract": false,
//         "Latitude": 60.14450000,
//         "Longitude": 29.48380000
//     },
//     {
//         "StationId": 87,
//         "StationName": "Adam Mickiewicz University Polar Station",
//         "Contact": null,
//         "Website": "www.amu.edu.pl",
//         "Email": "svalbard@amu.edu.pl",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "AMUPS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "AMUPS1-975x400.jpg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 78.41000000,
//         "Longitude": 16.27000000
//     },
//     {
//         "StationId": 88,
//         "StationName": "Churchill Northern Studies Centre",
//         "Contact": null,
//         "Website": "www.churchillscience.ca",
//         "Email": "research@churchillscience.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CNSC",
//         "Confirm": null,
//         "Reject": null,
//         "Image": null,
//         "HasSignedGPDRContract": false,
//         "Latitude": 58.73745277,
//         "Longitude": -93.81902222
//     },
//     {
//         "StationId": 89,
//         "StationName": "CEN Kangiqsualujjuaq Sukuijarvik Research Station",
//         "Contact": null,
//         "Website": "http://www.cen.ulaval.ca/en/station.php?id=505176&nm=kangiq",
//         "Email": "station@cen.ulaval.ca",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "CEN Kangiqsualujjuaq",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "CBarnard12_CEN.JPG",
//         "HasSignedGPDRContract": false,
//         "Latitude": 58.42000000,
//         "Longitude": -65.59000000
//     },
//     {
//         "StationId": 90,
//         "StationName": "The DMI Geophysical Observatory Qaanaaq",
//         "Contact": null,
//         "Website": "www.dmi.dk",
//         "Email": "smo@dmi.dk",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "DMI",
//         "Confirm": null,
//         "Reject": null,
//         "Image": null,
//         "HasSignedGPDRContract": false,
//         "Latitude": 77.28000000,
//         "Longitude": -69.13000000
//     },
//     {
//         "StationId": 91,
//         "StationName": "Skálanes Research Station",
//         "Contact": null,
//         "Website": "www.skalanes.com",
//         "Email": "skalanes@skalanes.com",
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "SRS",
//         "Confirm": null,
//         "Reject": null,
//         "Image": "IcelandSept08-078-640x400.jpeg",
//         "HasSignedGPDRContract": false,
//         "Latitude": 65.14000000,
//         "Longitude": -13.70000000
//     },
//     {
//         "StationId": 92,
//         "StationName": "Karkonosze Mountains National Parks",
//         "Contact": null,
//         "Website": null,
//         "Email": null,
//         "AdminId": null,
//         "Terms": null,
//         "Acronym": "KMPL",
//         "Confirm": null,
//         "Reject": null,
//         "Image": null,
//         "HasSignedGPDRContract": false,
//         "Latitude": 50.73333300,
//         "Longitude": 15.73333300
//     },
    {
        "StationId": 93,
        "StationName": "Nicolaus Copernicus University Polar Station",
        "Contact": null,
        "Website": "http://www.home.umk.pl/~geopolar/stacja/english.htm",
        "Email": "irso@umk.pl",
        "AdminId": null,
        "Terms": null,
        "Acronym": "NCUPS",
        "Confirm": null,
        "Reject": null,
        "Image": "NCUPS-975x400.jpg",
        "HasSignedGPDRContract": false,
        "Latitude": 78.67607830,
        "Longitude": 11.81907170
    },
    {
        "StationId": 97,
        "StationName": "Polar Station Petuniabuka",
        "Contact": null,
        "Website": "https://polar.amu.edu.pl",
        "Email": "svalbard@amu.edu.pl",
        "AdminId": null,
        "Terms": null,
        "Acronym": "PTNB",
        "Confirm": null,
        "Reject": null,
        "Image": null,
        "HasSignedGPDRContract": false,
        "Latitude": 78.686581731,
        "Longitude": 16.456684856
    },
    {
        "StationId": 96,
        "StationName": "AWIPEV Arctic Research Base",
        "Contact": null,
        "Website": "https://www.awipev.eu/",
        "Email": "station@awipev.eu",
        "AdminId": null,
        "Terms": null,
        "Acronym": "AWIPEV",
        "Confirm": null,
        "Reject": null,
        "Image": null,
        "HasSignedGPDRContract": false,
        "Latitude": 79.523485978,
        "Longitude": 11.622842106
    }
]